from src.config.studies.models import (
    ExperimentSpec,
    RandomNavigationProtocol,
    StudyConfig,
)


PPO_NAVIGATION_VEHICLE_TEMPORAL_FUSION = StudyConfig(
    study_id="PPO_NAVIGATION_VEHICLE_TEMPORAL_FUSION",
    description=(
        "Focused navigation ablation that holds the PPO exp=26 backbone fixed "
        "while varying mask-time postprocessing for vehicle motion cues."
    ),
    optuna_study_name="PPO_NAVIGATION_VEHICLE_TEMPORAL_FUSION",
    db_path="results/ppo_navigation_vehicle_temporal_fusion_optuna.db",
    metadata={
        "owner": "carlabev-lab",
        "kind": "navigation",
        "parent_study_id": "PPO_NAVIGATION",
        "parent_exp_id": 26,
        "design": "temporal_fusion_mode x fov_anchor full factorial",
        "notes": (
            "All runs hold the PPO navigation exp=26 backbone fixed: "
            "discrete actions, traffic on, mask input, 6-class semantics, "
            "CARL reward, route-only curriculum, and FOV masking off."
        ),
    },
    train_protocols={
        "random_nav_train": RandomNavigationProtocol(
            protocol_id="random_nav_train",
            mode="random_navigation",
            initial_num_vehicles=0,
            initial_route_dist_range=(50, 150),
            use_curriculum=True,
        ),
    },
    eval_protocols={
        "random_nav_eval": RandomNavigationProtocol(
            protocol_id="random_nav_eval",
            mode="random_navigation",
            initial_num_vehicles=25,
            initial_route_dist_range=(250, 500),
            eval_num_vehicles=25,
            eval_route_dist_range=(250, 500),
            use_curriculum=False,
        ),
    },
    experiments={
        1: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            temporal_fusion_mode="stack",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["fusion-sweep", "stack", "center", "baseline-match"],
            notes="Exact observation baseline matching PPO_NAVIGATION exp=26.",
        ),
        2: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            temporal_fusion_mode="vehicle_temporal",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["fusion-sweep", "vehicle_temporal", "center"],
            notes="Current-frame static semantics plus vehicle_t/t-1/t-2 channels.",
        ),
        3: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            temporal_fusion_mode="vehicle_weighted",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["fusion-sweep", "vehicle_weighted", "center"],
            notes="Current-frame static semantics plus one decayed vehicle-history channel.",
        ),
        4: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            temporal_fusion_mode="stack",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["fusion-sweep", "stack", "lookahead_75", "baseline-lookahead"],
            notes="Stacked semantic baseline with lookahead_75 anchor.",
        ),
        5: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            temporal_fusion_mode="vehicle_temporal",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["fusion-sweep", "vehicle_temporal", "lookahead_75"],
            notes="Vehicle temporal fusion with lookahead_75 anchor.",
        ),
        6: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            temporal_fusion_mode="vehicle_weighted",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["fusion-sweep", "vehicle_weighted", "lookahead_75"],
            notes="Weighted vehicle history fusion with lookahead_75 anchor.",
        ),
    },
)
