from src.config.studies.models import (
    ExperimentSpec,
    RandomNavigationProtocol,
    StudyConfig,
)


PPO_NAVIGATION = StudyConfig(
    study_id="PPO_NAVIGATION",
    description="Primary PPO navigation study covering action space, traffic, input, reward, curriculum, and FOV masking variants.",
    optuna_study_name="PPO_NAVIGATION",
    db_path="results/ppo_navigation_optuna.db",
    metadata={
        "owner": "carlabev-lab",
        "kind": "navigation",
        "notes": "Migrated from the legacy global EXPERIMENT_TABLE navigation matrix.",
    },
    train_protocols={
        "random_nav_train": RandomNavigationProtocol(
            protocol_id="random_nav_train",
            mode="random_navigation",
            initial_num_vehicles=0,
            initial_route_dist_range=(50, 150),
            use_curriculum=True,
        ),
    },
    eval_protocols={
        "random_nav_eval": RandomNavigationProtocol(
            protocol_id="random_nav_eval",
            mode="random_navigation",
            initial_num_vehicles=25,
            initial_route_dist_range=(250, 500),
            eval_num_vehicles=25,
            eval_route_dist_range=(250, 500),
            use_curriculum=False,
        ),
    },
    experiments={
        1: ExperimentSpec(action_mode="discrete", traffic="off", input_type="rgb", reward_mode="shaping", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        2: ExperimentSpec(action_mode="discrete", traffic="off", input_type="rgb", reward_mode="shaping", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        3: ExperimentSpec(action_mode="discrete", traffic="off", input_type="rgb", reward_mode="carl", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        4: ExperimentSpec(action_mode="discrete", traffic="off", input_type="rgb", reward_mode="carl", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        5: ExperimentSpec(action_mode="discrete", traffic="off", input_type="masks", semantic_mask_ch="6-class", reward_mode="shaping", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        6: ExperimentSpec(action_mode="discrete", traffic="off", input_type="masks", semantic_mask_ch="6-class", reward_mode="shaping", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        7: ExperimentSpec(action_mode="discrete", traffic="off", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        8: ExperimentSpec(action_mode="discrete", traffic="off", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        9: ExperimentSpec(action_mode="discrete", traffic="on", input_type="rgb", reward_mode="shaping", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        10: ExperimentSpec(action_mode="discrete", traffic="on", input_type="rgb", reward_mode="shaping", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        11: ExperimentSpec(action_mode="discrete", traffic="on", input_type="rgb", reward_mode="carl", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        12: ExperimentSpec(action_mode="discrete", traffic="on", input_type="rgb", reward_mode="carl", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        13: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="shaping", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        14: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="shaping", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        15: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        16: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        17: ExperimentSpec(action_mode="discrete", traffic="on", input_type="rgb", reward_mode="carl", curriculum="vehicles_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        18: ExperimentSpec(action_mode="discrete", traffic="on", input_type="rgb", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        19: ExperimentSpec(action_mode="discrete", traffic="on", input_type="rgb", reward_mode="carl", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        20: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="vehicles_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        21: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        22: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="both", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        23: ExperimentSpec(action_mode="discrete", traffic="off", input_type="rgb", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        24: ExperimentSpec(action_mode="discrete", traffic="off", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        25: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="off", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"], notes="Navigation baseline without curriculum."),
        26: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        27: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="on", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        28: ExperimentSpec(action_mode="continuous", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        29: ExperimentSpec(action_mode="continuous", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="on", fov_anchor="center", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"]),
        30: ExperimentSpec(action_mode="discrete", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="lookahead_75", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"], notes="Route-only navigation with lookahead_75 FOV anchor."),
        31: ExperimentSpec(action_mode="continuous", traffic="on", input_type="masks", semantic_mask_ch="6-class", reward_mode="carl", curriculum="route_only", fov_mask="off", fov_anchor="lookahead_75", train_protocol_id="random_nav_train", eval_protocol_ids=["random_nav_eval"], notes="Continuous-control route-only navigation with lookahead_75 FOV anchor."),
    },
)
