from src.config.studies.models import (
    ExperimentSpec,
    RandomNavigationProtocol,
    StudyConfig,
)


PPO_NAVIGATION_SEMANTIC_LOOKAHEAD = StudyConfig(
    study_id="PPO_NAVIGATION_SEMANTIC_LOOKAHEAD",
    description=(
        "Focused navigation study that reruns the exp=26 PPO baseline while "
        "varying semantic mask granularity and FOV anchor placement."
    ),
    optuna_study_name="PPO_NAVIGATION_SEMANTIC_LOOKAHEAD",
    db_path="results/ppo_navigation_semantic_lookahead_optuna.db",
    metadata={
        "owner": "carlabev-lab",
        "kind": "navigation",
        "parent_study_id": "PPO_NAVIGATION",
        "parent_exp_id": 26,
        "design": "semantic_mask_ch x fov_anchor full factorial",
        "notes": (
            "All runs hold the PPO navigation exp=26 backbone fixed: "
            "discrete actions, traffic on, mask input, CARL reward, route-only "
            "curriculum, and FOV masking off."
        ),
    },
    train_protocols={
        "random_nav_train": RandomNavigationProtocol(
            protocol_id="random_nav_train",
            mode="random_navigation",
            initial_num_vehicles=0,
            initial_route_dist_range=(50, 150),
            use_curriculum=True,
        ),
    },
    eval_protocols={
        "random_nav_eval": RandomNavigationProtocol(
            protocol_id="random_nav_eval",
            mode="random_navigation",
            initial_num_vehicles=25,
            initial_route_dist_range=(250, 500),
            eval_num_vehicles=25,
            eval_route_dist_range=(250, 500),
            use_curriculum=False,
        ),
    },
    experiments={
        1: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="binary",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "binary", "center"],
            notes="Exp=26 backbone with binary semantic masks and centered ego anchor.",
        ),
        2: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="binary",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "binary", "lookahead_75"],
            notes="Exp=26 backbone with binary semantic masks and lookahead_75 ego anchor.",
        ),
        3: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="2-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "2-class", "center"],
            notes="Exp=26 backbone with 2-class semantic masks and centered ego anchor.",
        ),
        4: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="2-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "2-class", "lookahead_75"],
            notes="Exp=26 backbone with 2-class semantic masks and lookahead_75 ego anchor.",
        ),
        5: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="4-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "4-class", "center"],
            notes="Exp=26 backbone with 4-class semantic masks and centered ego anchor.",
        ),
        6: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="4-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "4-class", "lookahead_75"],
            notes="Exp=26 backbone with 4-class semantic masks and lookahead_75 ego anchor.",
        ),
        7: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="5-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "5-class", "center"],
            notes="Exp=26 backbone with 5-class semantic masks and centered ego anchor.",
        ),
        8: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="5-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "5-class", "lookahead_75"],
            notes="Exp=26 backbone with 5-class semantic masks and lookahead_75 ego anchor.",
        ),
        9: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "6-class", "center", "baseline-match"],
            notes="Exact semantic/anchor match to PPO_NAVIGATION exp=26.",
        ),
        10: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="6-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "6-class", "lookahead_75", "baseline-lookahead"],
            notes="Exact semantic/anchor match to PPO_NAVIGATION exp=30 except for study membership.",
        ),
        11: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="7-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="center",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "7-class", "center"],
            notes="Exp=26 backbone with 7-class semantic masks and centered ego anchor.",
        ),
        12: ExperimentSpec(
            action_mode="discrete",
            traffic="on",
            input_type="masks",
            semantic_mask_ch="7-class",
            reward_mode="carl",
            curriculum="route_only",
            fov_mask="off",
            fov_anchor="lookahead_75",
            train_protocol_id="random_nav_train",
            eval_protocol_ids=["random_nav_eval"],
            tags=["semantic-sweep", "7-class", "lookahead_75"],
            notes="Exp=26 backbone with 7-class semantic masks and lookahead_75 ego anchor.",
        ),
    },
)
