from src.config.studies.models import ExperimentSpec, StudyConfig


PPO_NAVIGATION = StudyConfig(
    study_id="PPO_NAVIGATION",
    description="Primary PPO navigation study covering action space, traffic, input, reward, curriculum, and FOV masking variants.",
    optuna_study_name="PPO_NAVIGATION",
    db_path="results/ppo_navigation_optuna.db",
    metadata={
        "owner": "carlabev-lab",
        "kind": "navigation",
        "notes": "Migrated from the legacy global EXPERIMENT_TABLE navigation matrix.",
    },
    experiments={
        1: ExperimentSpec(action_space="discrete", traffic="off", input_type="rgb", reward_type="shaping", curriculum="off", fov_mask="off"),
        2: ExperimentSpec(action_space="discrete", traffic="off", input_type="rgb", reward_type="shaping", curriculum="both", fov_mask="off"),
        3: ExperimentSpec(action_space="discrete", traffic="off", input_type="rgb", reward_type="carl", curriculum="off", fov_mask="off"),
        4: ExperimentSpec(action_space="discrete", traffic="off", input_type="rgb", reward_type="carl", curriculum="both", fov_mask="off"),
        5: ExperimentSpec(action_space="discrete", traffic="off", input_type="masks", reward_type="shaping", curriculum="off", fov_mask="off"),
        6: ExperimentSpec(action_space="discrete", traffic="off", input_type="masks", reward_type="shaping", curriculum="both", fov_mask="off"),
        7: ExperimentSpec(action_space="discrete", traffic="off", input_type="masks", reward_type="carl", curriculum="off", fov_mask="off"),
        8: ExperimentSpec(action_space="discrete", traffic="off", input_type="masks", reward_type="carl", curriculum="both", fov_mask="off"),
        9: ExperimentSpec(action_space="discrete", traffic="on", input_type="rgb", reward_type="shaping", curriculum="off", fov_mask="off"),
        10: ExperimentSpec(action_space="discrete", traffic="on", input_type="rgb", reward_type="shaping", curriculum="both", fov_mask="off"),
        11: ExperimentSpec(action_space="discrete", traffic="on", input_type="rgb", reward_type="carl", curriculum="off", fov_mask="off"),
        12: ExperimentSpec(action_space="discrete", traffic="on", input_type="rgb", reward_type="carl", curriculum="both", fov_mask="off"),
        13: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="shaping", curriculum="off", fov_mask="off"),
        14: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="shaping", curriculum="both", fov_mask="off"),
        15: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="off", fov_mask="off"),
        16: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="both", fov_mask="off"),
        17: ExperimentSpec(action_space="discrete", traffic="on", input_type="rgb", reward_type="carl", curriculum="vehicles_only", fov_mask="off"),
        18: ExperimentSpec(action_space="discrete", traffic="on", input_type="rgb", reward_type="carl", curriculum="route_only", fov_mask="off"),
        19: ExperimentSpec(action_space="discrete", traffic="on", input_type="rgb", reward_type="carl", curriculum="both", fov_mask="off"),
        20: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="vehicles_only", fov_mask="off"),
        21: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="route_only", fov_mask="off"),
        22: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="both", fov_mask="off"),
        23: ExperimentSpec(action_space="discrete", traffic="off", input_type="rgb", reward_type="carl", curriculum="route_only", fov_mask="off"),
        24: ExperimentSpec(action_space="discrete", traffic="off", input_type="masks", reward_type="carl", curriculum="route_only", fov_mask="off"),
        25: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="off", fov_mask="off", notes="Navigation baseline without curriculum."),
        26: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="route_only", fov_mask="off"),
        27: ExperimentSpec(action_space="discrete", traffic="on", input_type="masks", reward_type="carl", curriculum="route_only", fov_mask="on"),
        28: ExperimentSpec(action_space="continuous", traffic="on", input_type="masks", reward_type="carl", curriculum="route_only", fov_mask="off"),
        29: ExperimentSpec(action_space="continuous", traffic="on", input_type="masks", reward_type="carl", curriculum="route_only", fov_mask="on"),
    },
)
