#!/bin/bash

set -euo pipefail

CARLABEV_REPO_ROOT="${CARLABEV_REPO_ROOT:-${SLURM_SUBMIT_DIR:-$(pwd)}}"
CARLABEV_ARTIFACT_ROOT="${CARLABEV_ARTIFACT_ROOT:-/data/horse/ws/dama898h-carlabev}"
CARLABEV_RESULTS_ROOT="${CARLABEV_RESULTS_ROOT:-${CARLABEV_ARTIFACT_ROOT}/results}"
CARLABEV_RUNS_ROOT="${CARLABEV_RUNS_ROOT:-${CARLABEV_ARTIFACT_ROOT}/runs}"
CARLABEV_DATASETS_ROOT="${CARLABEV_DATASETS_ROOT:-${CARLABEV_ARTIFACT_ROOT}/datasets}"

export CARLABEV_REPO_ROOT
export CARLABEV_ARTIFACT_ROOT
export CARLABEV_RESULTS_ROOT
export CARLABEV_RUNS_ROOT
export CARLABEV_DATASETS_ROOT

mkdir -p "${CARLABEV_RESULTS_ROOT}/logs"
mkdir -p "${CARLABEV_RUNS_ROOT}"
mkdir -p "${CARLABEV_DATASETS_ROOT}"
